//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTTour()
        {
            this.DonDatTours = new HashSet<DonDatTour>();
        }
    
        public int MaTour { get; set; }
        public System.DateTime NgayXP { get; set; }
        public Nullable<int> SoLuongCho { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaKM { get; set; }
        //public double DonGia { get { return (double.Parse(Tour.Gia.ToString()) * (100 - int.Parse(KhuyenMai.PhanTram.ToString())) / 100); } set { DonGia = (double.Parse(Tour.Gia.ToString()) * (100 - int.Parse(KhuyenMai.PhanTram.ToString())) / 100); } }
        public virtual Tour Tour { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatTour> DonDatTours { get; set; }
    }
}
