//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatTour()
        {
            this.CTDonDatTours = new HashSet<CTDonDatTour>();
        }
    
        public int MaDon { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaTour { get; set; }
        public Nullable<System.DateTime> NgayXP { get; set; }
        public Nullable<System.DateTime> TGDatTour { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public string GhiChu { get; set; }
        public string PTThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> TTThanhToan { get; set; }
        public Nullable<int> TreEm { get; set; }

        //CTTour.Tour.Gia*(100-(CTTout.KhuyenMai.PhanTram))/100
        public double ThanhTien { get { return (double.Parse((CTTour.Tour.Gia * (100 - (CTTour.KhuyenMai.PhanTram)) / 100).ToString()) * int.Parse(SoLuongKhach.ToString()))-(double.Parse((CTTour.Tour.Gia * (100 - (CTTour.KhuyenMai.PhanTram)) / 100).ToString()) * 0.25 * int.Parse(TreEm.ToString())); } }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonDatTour> CTDonDatTours { get; set; }
        public virtual CTTour CTTour { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
