//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTin { get; set; }
        public string TieuDe { get; set; }
        public string Anh { get; set; }
        public Nullable<System.DateTime> TGDangTin { get; set; }
        public Nullable<int> MaLoaiTin { get; set; }
        public string NoiDung { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual LoaiTinTuc LoaiTinTuc { get; set; }
    }
}
