//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.CTTours = new HashSet<CTTour>();
        }
    
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public Nullable<int> MaLoaiTour { get; set; }
        public string GioiThieu { get; set; }
        public string ChuongTrinh { get; set; }
        public string Anh { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaDiemXP { get; set; }
        public int MaDiemDen { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> LuotDanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTour> CTTours { get; set; }
        public virtual DiemDen DiemDen { get; set; }
        public virtual DiemXP DiemXP { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
    }
}
